test-api:
  stage: test
  coverage: '/TOTAL.*\s+(\d+%)$/'
  script:
    - sh ./scripts/gitlab-test-api.sh
  tags:
    - test

test-data-retrieval:
  stage: test
  coverage: '/TOTAL.*\s+(\d+%)$/'
  script:
    - sh ./scripts/gitlab-test-data-retrieval.sh
  tags:
    - test

build-and-push:
  stage: deploy
  script:
    - sh ./scripts/gitlab-build-and-push.sh
  tags:
    - deploy

push-to-prod:
  stage: deploy
  script:
    - sh ./scripts/gitlab-push-to-prod.sh
  tags:
    - deploy
  rules:
    - if: '$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME == "main"'

