services:
  nosql-db-deployment:
    image: mongo:8.0
    restart: "no"
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

    env_file:
      - .env-deployment
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_DATABASE}
    volumes:
      - prod-app-nosql-db-data:/data/db

  sql-db-deployment:
    image: postgres:12
    restart: "no"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    volumes:
      - prod-app-db-data:/var/lib/postgresql/data/pgdata
    env_file:
      - .env-deployment
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD?Variable not set}
      - POSTGRES_USER=${POSTGRES_USER?Variable not set}
      - POSTGRES_DB=${POSTGRES_DB?Variable not set}

  backend-api-deployment:
    image: '${DOCKER_IMAGE_BACKEND?Variable not set}:${TAG-latest}'
    restart: "no"
    networks:
      - default
    depends_on:
      sql-db:
        condition: service_healthy
#        restart: true
    env_file:
      - .env-deployment
    ports:
      - "8001:8000"

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/utils/health-check/"]
      interval: 10s
      timeout: 5s
      retries: 5

    build:
      context: ./api

  frontend-deployment:
    image: '${DOCKER_IMAGE_FRONTEND?Variable not set}:${TAG-latest}'
    build:
      context: ./frontend
      args:
        NEXT_PUBLIC_API_BASE_URL: http://runner.bearded-tetra.ts.net:8001/api/v1
    ports:
      - "80:3000"
    environment:
      - NEXT_PUBLIC_API_BASE_URL=http://runner.bearded-tetra.ts.net:8001/api/v1
      - NODE_ENV=production
    restart: "no"
    networks:
      - default
    depends_on:
      backend-api:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 10s
      timeout: 5s
      retries: 5

  data-retrieval-deployment:
    image: '${DOCKER_IMAGE_DATA_RETRIEVAL?Variable not set}:${TAG-latest}'
    restart: "no"
    networks:
      - default
    build:
        context: ./data_retrieval
    depends_on:
      nosql-db:
        condition: service_healthy
    env_file:
      - .env-deployment
    environment:
      - MONGO_HOST=${MONGO_HOST}
      - MONGO_PORT=${MONGO_PORT}
      - MONGO_USERNAME=${MONGO_USERNAME}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - MONGO_DATABASE=${MONGO_DATABASE}
      - WARSAW_API_URL=${WARSAW_API_URL}
      - WARSAW_API_KEY=${WARSAW_API_KEY}
      - HEARTBEAT=${HEARTBEAT}
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"

  postgres-exporter:
    profiles:
      - deployment
    image: quay.io/prometheuscommunity/postgres-exporter
    container_name: postgres-exporter
    depends_on:
        sql-db:
          condition: service_healthy
    networks:
        - default
    env_file:
      - .env-deployment
    environment:
      - DATA_SOURCE_URI=${POSTGRES_HOST}:${POSTGRES_PORT}/postgres?sslmode=disable
      - DATA_SOURCE_USER=${POSTGRES_USER}
      - DATA_SOURCE_PASS=${POSTGRES_PASSWORD}
  mongo-exporter:
    profiles:
      - deployment
    networks:
        - default
    image: bitnami/mongodb-exporter:0.11.0-debian-10-r75
    env_file:
      - .env-deployment
    environment:
      - MONGODB_URI=mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@${MONGO_HOST}:27018

  prometheus:
    profiles:
      - deployment
    image: prom/prometheus
    container_name: prometheus
    networks:
        - default
    ports:
      - '9090:9090'
    env_file:
      - .env-deployment
    volumes:
      - './grafana/prometheus:/etc/prometheus'
    command: '--config.file=/etc/prometheus/prometheus.yml'

  grafana:
      profiles:
        - deployment
      image: grafana/grafana-enterprise
      container_name: grafana
      restart: unless-stopped
      env_file:
        - .env-deployment
      env_file:
        - .env-deployment
      environment:
        - DATABASE_SSL_MODE=disable
        - GF_LOG_LEVEL=debug
        - POSTGRES_HOST=${POSTGRES_HOST}
        - POSTGRES_PORT=${POSTGRES_PORT}
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - POSTGRES_DATABASE=${POSTGRES_DB}
      ports:
        - '4100:3000'
      volumes:
        - './grafana/config/grafana.ini:/etc/grafana/grafana.ini'
        - './grafana/provisioning:/etc/grafana/provisioning'
        - 'prod-grafana_storage:/var/lib/grafana'
      networks:
        - default

volumes:
  prod-app-db-data:
  prod-app-nosql-db-data:
  prod-grafana_storage:

networks:
  default:
    driver: bridge