global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: postgres
    static_configs:
        - targets: [ "postgres-exporter:9187" ]
  - job_name: mongodb
    static_configs:
        - targets: [ "mongo-exporter:9216" ]